[package]
name = "taskchampion-lib"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.73.0"  # MSRV

[lib]
crate-type = ["staticlib"]

[dependencies]
taskchampion = "0.9.0"
# All three cxx* dependencies must have precisely the same version.
cxx = "=1.0.124"

[features]
# use native CA roots, instead of bundled
tls-native-roots = ["taskchampion/tls-native-roots"]

[build-dependencies]
# All three cxx* dependencies must have precisely the same version.
cxx-build = "=1.0.124"

# Include cxxbridge-cmd in Cargo.lock along with the others. This gives a
# warning "ignoring invalid dependency `cxxbridge-cmd` which is missing a lib
# target" but this can be safely ignored.
# See https://github.com/dtolnay/cxx/issues/1407#issuecomment-2509136343
[target.'cfg(any())'.dependencies]
# All three cxx* dependencies must have precisely the same version.
cxxbridge-cmd = "=1.0.124"
